name: Windows

on: 
  push:

jobs:
  test-suite:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - name: Start Windows Audio Engine
        run: net start audiosrv
      - name: Install Scream
        shell: powershell
        run: |
          Start-Service audio*
          Invoke-WebRequest https://github.com/duncanthrax/scream/releases/download/3.6/Scream3.6.zip -OutFile C:\Scream3.6.zip
          Extract-7Zip -Path C:\Scream3.6.zip -DestinationPath C:\Scream
          $cert = (Get-AuthenticodeSignature C:\Scream\Install\driver\Scream.sys).SignerCertificate
          $store = [System.Security.Cryptography.X509Certificates.X509Store]::new("TrustedPublisher", "LocalMachine")
          $store.Open("ReadWrite")
          $store.Add($cert)
          $store.Close()
          cd C:\Scream\Install\driver
          C:\Scream\Install\helpers\devcon install Scream.inf *Scream
      - name: Show audio device
        run: Get-CimInstance Win32_SoundDevice | fl *
      - name: Download GUI
        shell: powershell
        run: |
          Invoke-WebRequest https://openephysgui.jfrog.io/artifactory/Dev/windows/open-ephys-v0.6.3-dev-windows.zip -OutFile C:\open-ephys.zip
          Extract-7Zip -Path C:\open-ephys.zip -DestinationPath C:\open-ephys
          New-Item -Path 'C:\open-ephys\data' -ItemType Directory
          Get-ChildItem -Path C:\open-ephys -Recurse -Directory -Force -ErrorAction SilentlyContinue | Select-Object FullName
      - name: Install test-suite
        shell: powershell
        run: |
          pip install git+https://github.com/open-ephys/open-ephys-python-tools.git@0.6.0    
      - name: Test Basic Acquisition
        shell: powershell
        run: |
          & C:\open-ephys\open-ephys.exe
          Start-Sleep -Seconds 5
          python tests\basic_acquire.py --mode githubactions    
      - name: Test Get/Set Recording Info
        shell: powershell
        run: |
          & C:\open-ephys\open-ephys.exe configs\file_reader_config.xml
          Start-Sleep -Seconds 5
          python tests\get_set_recording_info.py --mode githubactions    
          Get-ChildItem -Path C:\open-ephys\data -Recurse -Directory -Force -ErrorAction SilentlyContinue | Select-Object FullName
      - name: Test Add/Delete processors
        shell: powershell
        run: |
          & C:\open-ephys\open-ephys.exe configs\file_reader_config.xml
          Start-Sleep -Seconds 5
          python tests\add_delete_processors.py --mode githubactions  
      - name: Test Basic Record
        shell: powershell
        run: |
          & C:\open-ephys\open-ephys.exe configs\file_reader_config.xml
          Start-Sleep -Seconds 5
          python tests\basic_record.py --mode githubactions 
      - name: Round Trip Test
        shell: powershell
        run: |
          Copy-Item "plugins\NWBFormat.dll" -Destination "C:\open-ephys\plugins"
          Copy-Item "plugins\open-ephys-data-format.dll" -Destination "C:\open-ephys\plugins"
          Copy-Item "shared\hdf5_cpp.dll" -Destination "C:\open-ephys\shared"
          Copy-Item "shared\hdf5.dll" -Destination "C:\open-ephys\shared"
          Copy-Item "shared\OpenEphysHDF5.dll" -Destination "C:\open-ephys\shared"
          Start-Sleep -Seconds 4
          & C:\open-ephys\open-ephys.exe configs\file_reader_config.xml
          Start-Sleep -Seconds 10
          python tests\round_trip_record.py --mode githubactions